In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
#Reading in the dataset
df = pd.read_csv("heart_2020_cleaned.csv")
df.head(10)


HeartDisease    BMI Smoking AlcoholDrinking Stroke  PhysicalHealth  \
0           No  16.60     Yes              No     No             3.0   
1           No  20.34      No              No    Yes             0.0   
2           No  26.58     Yes              No     No            20.0   
3           No  24.21      No              No     No             0.0   
4           No  23.71      No              No     No            28.0   
5          Yes  28.87     Yes              No     No             6.0   
6           No  21.63      No              No     No            15.0   
7           No  31.64     Yes              No     No             5.0   
8           No  26.45      No              No     No             0.0   
9           No  40.69      No              No     No             0.0   

   MentalHealth DiffWalking     Sex  AgeCategory   Race  \
0          30.0          No  Female        55-59  White   
1           0.0          No  Female  80 or older  White   
2          30.0          No    Male        65-69  White   
3           0.0          No  Female        75-79  White   
4           0.0         Yes  Female        40-44  White   
5           0.0         Yes  Female        75-79  Black   
6           0.0          No  Female        70-74  White   
7           0.0         Yes  Female  80 or older  White   
8           0.0          No  Female  80 or older  White   
9           0.0         Yes    Male        65-69  White   

                  Diabetic PhysicalActivity  GenHealth  SleepTime Asthma  \
0                      Yes              Yes  Very good        5.0    Yes   
1                       No              Yes  Very good        7.0     No   
2                      Yes              Yes       Fair        8.0    Yes   
3                       No               No       Good        6.0     No   
4                       No              Yes  Very good        8.0     No   
5                       No               No       Fair       12.0     No   
6                       No              Yes       Fair        4.0    Yes   
7                      Yes               No       Good        9.0    Yes   
8  No, borderline diabetes               No       Fair        5.0     No   
9                       No              Yes       Good       10.0     No   

  KidneyDisease SkinCancer  
0            No        Yes  
1            No         No  
2            No         No  
3            No        Yes  
4            No         No  
5            No         No  
6            No        Yes  
7            No         No  
8           Yes         No  
9            No         No

In [3]:
heart=df[["HeartDisease","Smoking","AlcoholDrinking","Stroke","PhysicalActivity","GenHealth"]]
heart.head()


HeartDisease Smoking AlcoholDrinking Stroke PhysicalActivity  GenHealth
0           No     Yes              No     No              Yes  Very good
1           No      No              No    Yes              Yes  Very good
2           No     Yes              No     No              Yes       Fair
3           No      No              No     No               No       Good
4           No      No              No     No              Yes  Very good

In [4]:
heart["GenHealth"].unique()

array(['Very good', 'Fair', 'Good', 'Poor', 'Excellent'], dtype=object)

In [5]:
#Translating "Yes" and "No" to Binary Values

heartdf=pd.DataFrame(heart["HeartDisease"])
smokingdf=pd.DataFrame(heart["Smoking"])
alcoholdf=pd.DataFrame(heart["AlcoholDrinking"])
strokedf=pd.DataFrame(heart["Stroke"])
physicaldf=pd.DataFrame(heart["PhysicalActivity"])

binarylistphysicalactivity=[]
binarylistheartdisease=[]
binarylistsmoking=[]
binarylistdrinking=[]
binaryliststroke=[]

for index, row in heartdf.iterrows():
    if(row["HeartDisease"]=="Yes"):
        #print(row["HeartDisease"])
        binarylistheartdisease.append(1)
    elif(row["HeartDisease"]=="No"):
        binarylistheartdisease.append(0)
heartdf["HeartDisease"]=binarylistheartdisease

for index, row in smokingdf.iterrows():
    if(row["Smoking"]=="Yes"):
        #print(row["HeartDisease"])
        binarylistsmoking.append(1)
    elif(row["Smoking"]=="No"):
        binarylistsmoking.append(0)
smokingdf["Smoking"]=binarylistsmoking

#smokingdf

for index, row in alcoholdf.iterrows():
    if(row["AlcoholDrinking"]=="Yes"):
        #print(row["HeartDisease"])
        binarylistdrinking.append(1)
    elif(row["AlcoholDrinking"]=="No"):
        binarylistdrinking.append(0)
alcoholdf["AlcoholDrinking"]=binarylistdrinking

for index, row in physicaldf.iterrows():
    if(row["PhysicalActivity"]=="Yes"):
        binarylistphysicalactivity.append(1)
    elif(row["PhysicalActivity"]=="No"):
        binarylistphysicalactivity.append(0)
physicaldf["PhysicalActivity"]=binarylistphysicalactivity

for index, row in strokedf.iterrows():
    if(row["Stroke"]=="Yes"):
        binaryliststroke.append(1)
    elif(row["Stroke"]=="No"):
        binaryliststroke.append(0)
strokedf["Stroke"]=binaryliststroke


physicaldf.head()


PhysicalActivity
0                 1
1                 1
2                 1
3                 0
4                 1

In [6]:
#Getting a new data frame with all the coded values

In [7]:
newdf=pd.get_dummies(df["GenHealth"])

#newdf=pd.get_dummies(df["PhysicalActivity"])

newdf["PhysicalActivity"]=physicaldf
#newdf["HeartDisease"]=heartdf
newdf["Smoking"]=smokingdf
newdf["AlcoholDrinking"]=alcoholdf
newdf["Stroke"]=strokedf
newdf.head()



Excellent  Fair  Good  Poor  Very good  PhysicalActivity  Smoking  \
0          0     0     0     0          1                 1        1   
1          0     0     0     0          1                 1        0   
2          0     1     0     0          0                 1        1   
3          0     0     1     0          0                 0        0   
4          0     0     0     0          1                 1        0   

   AlcoholDrinking  Stroke  
0                0       0  
1                0       1  
2                0       0  
3                0       0  
4                0       0

## Creating the model

In [8]:

X = newdf
label = df["HeartDisease"]


#the model:
from sklearn.naive_bayes import BernoulliNB
model  = BernoulliNB() #create
model.fit(X,label) #training

 


BernoulliNB()

## Model Results and Validation

### Cross Validation

In [9]:
from sklearn.model_selection import cross_val_score #validation and scoring
print(cross_val_score(model,X,label,cv=5)) #model name, whole df, labels
cv5=cross_val_score(model,X,label,cv=5).mean()
cv5

[0.90875405 0.91025501 0.90933254 0.90853516 0.90991104]


0.9093575571850717

In [10]:
print(cross_val_score(model,X,label,cv=10)) #model name, whole df, labels
cv10=cross_val_score(model,X,label,cv=10).mean()
cv10

[0.91028768 0.90722326 0.91035022 0.91010006 0.90888055 0.90978455
 0.90859627 0.90850245 0.91037869 0.90947184]


0.9093575570162414

In [11]:
print(cross_val_score(model,X,label,cv=3)) #model name, whole df, labels
cv3=cross_val_score(model,X,label,cv=3).mean()
cv3

[0.90927682 0.9098576  0.90893825]


0.9093575574375302

In [12]:
pip install tabulate

Note: you may need to restart the kernel to use updated packages.


In [13]:
from tabulate import tabulate
table = [['Accuracy Score',"K Value"], [cv3, 3], [cv5, 5], [cv10, 10]]
print(tabulate(table))

------------------  -------
Accuracy Score      K Value
0.9093575574375302  3
0.9093575571850717  5
0.9093575570162414  10
------------------  -------


## Confusion Matrix with Cross Validation Scores

In [14]:
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import confusion_matrix
y_pred = cross_val_predict(model, X, label, cv=3)
conf_mat = confusion_matrix(label, y_pred)

print("K Value of 3")
print(conf_mat)

K Value of 3
[[286912   5510]
 [ 23477   3896]]


In [15]:
y_pred1 = cross_val_predict(model, X, label, cv=5)
conf_mat1 = confusion_matrix(label, y_pred1)

print("K Value of 5")
print(conf_mat1)

K Value of 5
[[286912   5510]
 [ 23477   3896]]


In [16]:
y_pred2 = cross_val_predict(model, X, label, cv=10)
conf_mat2 = confusion_matrix(label, y_pred)

print("K Value of 10")
print(conf_mat2)

K Value of 10
[[286912   5510]
 [ 23477   3896]]


## Final Model Results and Validation

In [17]:
### Confusion Matrix

In [18]:
y_pred1 = cross_val_predict(model, X, label, cv=5)
conf_mat1 = confusion_matrix(label, y_pred1)

print("K Value of 5")
print(conf_mat1)

K Value of 5
[[286912   5510]
 [ 23477   3896]]


In [19]:
### Accuracy Score with Cross Validation

In [20]:
print("Accuracy Score: ",cv5)

Accuracy Score:  0.9093575571850717
